version: "2"
services:
  offerdatabase:
    image: postgres
    environment:
      - POSTGRES_USER=offer
      - POSTGRES_PASSWORD=123offerabc
      - POSTGRES_DB=offer
    ports:
      - 5433:5432
    volumes:
      - ./postgres_scripts/offer:/docker-entrypoint-initdb.d
      - ./sample_data/offer:/tmp
  conversiondatabase:
    image: postgres
    environment:
      - POSTGRES_USER=conversion
      - POSTGRES_PASSWORD=123conversionabc
      - POSTGRES_DB=conversion
    ports:
      - 5434:5432
    volumes:
      - ./postgres_scripts/conversion:/docker-entrypoint-initdb.d

